@baseURL = http://localhost:4000
@cpf = 754.214.735-89
@cpf2 = 527.975.133-20
@cpf3 = 539.456.672-08
###
// GET - Lista of alunos
GET {{baseURL}}/alunos
Content-Type: application/json

###
// GET - Lista um aluno pelo cfp
GET {{baseURL}}/alunos/{{cpf}}
Content-Type: application/json

###
// POST - Inclui novo aluno
POST {{baseURL}}/alunos
Content-Type: application/json

{"nome": "Jo",
"dataMatricula":"2000/12/31", 
"estaAtivo": true,
"cpf":"539.456.672-08",
"foto": {
       "originalname": "massas2.png", 
       "path": "public/uploads/massas.png",
       "size": 20771, 
       "mimetype":"image/png"
  }
}

###
// DELETE - Apaga uma categoria
DELETE {{baseURL}}/alunos/{{cpf2}}
Content-Type: application/json

###
// PUT - Altera a categoria
PUT {{baseURL}}/alunos
Content-Type: application/json

{
"cpf" : "539.456.672-08",
"dataMatricula":"2020/01/01",
"nome" : "José Jovia revengence",
"status": true
}